cache:
  untracked: true
goBuild:
  stage: build
  image: weavelab/weavebuilder:$WEAVE_BUILDER_VERSION
  script:
    - /usr/local/bin/weavebuilder
cdTools:
  stage: deploy
  image: weavelab/cd-tools:v1.0.0
  script:
    - /bin/cd-tools
